#!/bin/bash

# Usage: $0 <image> <regex> <postfix>

usage(){
    echo "Usage: $0 -i <image> -r <regex> [-p postfix]
      -i image: docker image to start from
      -r regex: regular expression to select layers to purge
      -p postfix: postfix to apply at the end of the tag name
      -h : this help
    "
}

BINDIR=$(dirname $$0)
POSTFIX="-reduced"

while getopts i:r:p:h FLAG; do
  case $FLAG in
    i)
      IMAGE=$OPTARG
      ;;
    r)
      REGEX=$OPTARG
      ;;
    p)
      POSTFIX=$OPTARG
      ;;
    h)
      usage
      ;;
    \?)
      echo "Option -$OPTARG not allowed."
      usage
      ;;
  esac
done
shift $((OPTIND-1))
[ -z "$IMAGE" ] && usage && exit 1
[ -z "$REGEX" ] && usage && exit 1

docker save $IMAGE -o tmp.tar
mkdir tmp
cd tmp
tar xf ../tmp.tar
rm ../tmp.tar
node ../docker-purge.js "$REGEX" "$POSTFIX"
tar cf new.tar *
docker load -i new.tar
cd ..
rm -rf tmp

